image: robertofilho/maven # java7 com maven

# Parallel jobs, each line is a parallel build
generate-site:
  stage: build
  script:
    - mvn p2:site

# Deploy
deploy:
  stage: deploy
  script:
    - echo "Success!" # Zipar e jogar no gtech.site
  when: on_success
