image: frekele/java:jdk8 # java8 com maven

variables:
  PACKAGE_NAME: "p2-repository"
  PACKAGE_VERSION: "1.0.1"

stages:
  - deploy

cache:
  paths:
    - .m2/

site:
  stage: deploy
  script:
    - mvn p2:site -Dmaven.repo.local=$PWD/.m2 # Cache maven repository
    - ls
    - cd target/repository
    - tar -czvf site.tar.gz * # create the tar file
    # Send to bintray with curl
    - curl -T site.tar.gz -u${BINTRAY_API_USER}:${BINTRAY_API_KEY} -H "X-Bintray-Package:${PACKAGE_NAME}" -H "X-Bintray-Version:${PACKAGE_VERSION}" -H "X-Bintray-Explode:1" https://api.bintray.com/content/${BINTRAY_API_USER}/generic/${PACKAGE_NAME}/${PACKAGE_VERSION}/p2/
    # - aws s3 ls s3://updates.gtech.site/p2/ # Lista os
    # - aws s3 rm s3://updates.gtech.site/p2/* --recursive # Limpa o diretório
    # - aws s3 cp --recursive . s3://updates.gtech.site/p2/
  artifacts:
    name: "${CI_BUILD_STAGE}-${CI_BUILD_REF_NAME}"
    paths:
      - target/repository
