image: robertofilho/maven-java8:java8-awscli # java7 com maven

stages:
  - build
  - deploy

# Parallel jobs, each line is a parallel build
generate-site:
  stage: build
  script:
    - aws s3 ls s3://mvn.gtech.site/release/ # Check if aws is there
    - mvn p2:site
  artifacts:
    name: "${CI_BUILD_STAGE}-${CI_BUILD_REF_NAME}"
    paths:
      - target/repository

# Deploy
deploy:
  stage: deploy
  script:
    - aws s3 ls s3://updates.gtech.site/p2/ # Lista os
    - aws s3 rm s3://updates.gtech.site/p2/* --recursive # Limpa o diretório
    #- aws s3 cp --recursive . s3://updates.gtech.site/p2/
  when: on_success
